---
title       : TV Series IMDb Ratings
subtitle    : Does a TV series get better or worse?
author      : Bill Cruise
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Do I really want to continue watching this TV series?

* We've all asked ourselves this question after watching one or two episodes of a series.

* Some shows grab you right away and you're hooked.

* Others can take a while to build up to a compelling story.

--- .class #id 

## Find out instantly if a TV series gets better or worse over time

* Don't waste money on expensive DVD box sets that you won't watch.

* Don't waste time binge watching Netflix series that you'll stop halfway through.

* Find out which seasons are the best and worst without reading reviews.

---

## How does it work?

* Choose from over 9,000 TV series rated on IMDb.
* All episode ratings on IMDb for that series will be plotted.

```{r, echo=FALSE}
series <- readRDS(file="buffy.Rda")

colors <- c("blue", "red", "orange", "green2", "purple", "yellow3")
palette(colors)
numColors = 6
par(pin = c(5.4, 4.5))

plot(series$Rating ~ series$row.nums, col=series$Season,
                 main="Buffy the Vampire Slayer (1997) IMDb Episode Ratings",
                 xlab="Episodes", ylab="Ratings")
grid(col = "lightgray")

seasons <- unique(series$Season)
for (i in 1:length(seasons)) {
    mod <- lm(series$Rating[series$Season==seasons[i]] ~ series$row.nums[series$Season==seasons[i]])
    coeff <- summary(mod)$coefficients
    m <- coeff[2, 1]
    b <- coeff[1, 1]
    x0 <- min(series$row.nums[series$Season==seasons[i]])
    y0 <- m * x0 + b
    x1 <- max(series$row.nums[series$Season==seasons[i]])
    y1 <- m * x1 + b
    segments(x0, y0, x1, y1, col=colors[((seasons[i]-1) %% numColors)+1])
}

```

---

## What other information is available?

* Best Season

* Worst Season

* Number of Episodes

* Total number of IMDb user ratings

* Series trend line (optional)

* Whether the series gets better or worse over time

Try it out now at [TV Series IMDb Ratings]("https://billcruise.shinyapps.io/tv-ratings/")

